apiVersion: v1
kind: Secret
metadata:
  name: phpmyadmin-db-secret
type: Opaque
stringData:
  PMA_HOST: "rc1a-5t1d4i3946v0599l.mdb.yandexcloud.net"
  PMA_PORT: "3306"
  PMA_USER: "test"
  PMA_PASSWORD: "password1234"
